### ISSUE TITLE
能不能这样

### ISSUE THREAD

**Issue by ovsexia** [yimijianfang/MyScroll#1]
例如，当滚动条大于 0 时，执行A，小于等于0时，执行B

实际的应用场景有，当浏览网页时，向下滚动，网页的顶部导航条就隐藏，当向上滚动到顶部时，导航条又再次显示出来

**Comment by yimijianfang** [comment]
MyScroll设计之初考虑的是做滚动条偏移位置的事件监听，暂不考虑加到库中。
